server:
  port: 8888
spring:
  application:
    name: Config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/saravananjkm176/Centralized-Properties-Serve       
eureka:
  client:
     register-with-eureka: true
     fetch-registry: true
     serviceUrl:
       defaultZone: http://localhost:8761/eureka
     instance: localhost
     preferIpAddress: true
     lease-renewal-interval-in-seconds: 10
     lease-expiration-duration-in-seconds: 20    
 
city:
   name: Jayankondam    
   

 